title: Randy (Xian Xinglang)
email: contact@randy.ai # Placeholder, user can update
description: 17-year-old AI Developer | Swift Student Challenge Distinguished Winner
baseurl: ""
url: "https://Randy-sin.github.io"

# Build settings
markdown: kramdown
permalink: /:title/
include: ['_pages']
