title: Xian Xinglang
email: your-email@domain.com
description: Academic and personal website.
baseurl: "/xianxinglang.github.io"
url: "https://Randy-sin.github.io"

# Build settings
markdown: kramdown
permalink: /:title/
include: ['_pages']
